/**
 * The 22 Major Arcana. Names, keywords and short meanings in English and
 * Brazilian Portuguese. Card ids match the image file names (`00`..`21`).
 */
import type { CardDef } from '../engine/types';

type Row = [
  id: string,
  en: string,
  pt: string,
  kwEn: string[],
  kwPt: string[],
  uprightEn: string,
  uprightPt: string,
  reversedEn: string,
  reversedPt: string,
];

const rows: Row[] = [
  ['00', 'The Fool', 'O Louco', ['beginnings', 'innocence', 'leap of faith'], ['começos', 'inocência', 'salto de fé'],
    'A fresh start. Step forward with curiosity and trust the journey, even without a map.',
    'Um novo começo. Siga em frente com curiosidade e confie na jornada, mesmo sem mapa.',
    'Recklessness or fear of taking the first step. Look before you leap, but do leap.',
    'Imprudência ou medo de dar o primeiro passo. Olhe antes de pular, mas pule.'],
  ['01', 'The Magician', 'O Mago', ['will', 'skill', 'manifestation'], ['vontade', 'habilidade', 'manifestação'],
    'You have every tool you need. Focus your will and turn intention into action.',
    'Você tem todas as ferramentas de que precisa. Concentre sua vontade e transforme intenção em ação.',
    'Scattered energy, manipulation or untapped talent. Realign your means with your ends.',
    'Energia dispersa, manipulação ou talento não usado. Realinhe os meios com os fins.'],
  ['02', 'The High Priestess', 'A Sacerdotisa', ['intuition', 'mystery', 'inner voice'], ['intuição', 'mistério', 'voz interior'],
    'Listen to what is not being said. The answer is already inside you; be still and receive it.',
    'Ouça o que não está sendo dito. A resposta já está dentro de você; aquiete-se e receba-a.',
    'Ignored intuition, secrets or surface-level thinking. Go quieter, not louder.',
    'Intuição ignorada, segredos ou pensamento superficial. Vá mais fundo, não mais alto.'],
  ['03', 'The Empress', 'A Imperatriz', ['abundance', 'nurturing', 'creativity'], ['abundância', 'cuidado', 'criatividade'],
    'Growth, comfort and fertile ground. Nurture what you love and let it flourish.',
    'Crescimento, conforto e terreno fértil. Cuide do que você ama e deixe florescer.',
    'Creative block, dependence or neglect of self-care. Tend your own garden first.',
    'Bloqueio criativo, dependência ou negligência com o autocuidado. Cuide primeiro do seu jardim.'],
  ['04', 'The Emperor', 'O Imperador', ['structure', 'authority', 'stability'], ['estrutura', 'autoridade', 'estabilidade'],
    'Order and leadership. Build solid foundations and take responsibility for your domain.',
    'Ordem e liderança. Construa bases sólidas e assuma a responsabilidade pelo seu domínio.',
    'Rigidity, domination or lack of discipline. Power serves best when it protects.',
    'Rigidez, dominação ou falta de disciplina. O poder serve melhor quando protege.'],
  ['05', 'The Hierophant', 'O Papa', ['tradition', 'guidance', 'belief'], ['tradição', 'orientação', 'crença'],
    'Learn from established wisdom, mentors and shared values. Ritual gives shape to meaning.',
    'Aprenda com a sabedoria estabelecida, mentores e valores compartilhados. O ritual dá forma ao sentido.',
    'Dogma, conformity or rebellion against rules. Question the tradition, keep the truth.',
    'Dogma, conformismo ou rebeldia contra as regras. Questione a tradição, guarde a verdade.'],
  ['06', 'The Lovers', 'Os Enamorados', ['union', 'choice', 'harmony'], ['união', 'escolha', 'harmonia'],
    'A meaningful bond or a values-defining choice. Choose what aligns heart and mind.',
    'Um vínculo significativo ou uma escolha que define valores. Escolha o que alinha coração e mente.',
    'Disharmony, misaligned values or avoidance of a decision. Be honest about what you want.',
    'Desarmonia, valores desalinhados ou fuga de uma decisão. Seja honesto sobre o que quer.'],
  ['07', 'The Chariot', 'O Carro', ['determination', 'victory', 'control'], ['determinação', 'vitória', 'controle'],
    'Drive forward with focus. Opposing forces can be harnessed when the will is clear.',
    'Avance com foco. Forças opostas podem ser domadas quando a vontade é clara.',
    'Loss of direction, aggression or self-doubt. Steer before you accelerate.',
    'Perda de direção, agressividade ou dúvida. Dirija antes de acelerar.'],
  ['08', 'Strength', 'A Força', ['courage', 'compassion', 'inner strength'], ['coragem', 'compaixão', 'força interior'],
    'Gentle power. Patience and kindness tame what force cannot.',
    'Poder gentil. Paciência e bondade domam o que a força não consegue.',
    'Self-doubt, raw emotion or forcing outcomes. Softness is not weakness.',
    'Insegurança, emoção crua ou forçar resultados. Suavidade não é fraqueza.'],
  ['09', 'The Hermit', 'O Eremita', ['introspection', 'solitude', 'wisdom'], ['introspecção', 'solidão', 'sabedoria'],
    'Withdraw to seek your own light. Answers come in quiet reflection.',
    'Recolha-se para buscar sua própria luz. As respostas vêm na reflexão silenciosa.',
    'Isolation, loneliness or refusing help. Come back with what you learned.',
    'Isolamento, solidão ou recusa de ajuda. Volte com o que aprendeu.'],
  ['10', 'Wheel of Fortune', 'A Roda da Fortuna', ['cycles', 'change', 'destiny'], ['ciclos', 'mudança', 'destino'],
    'The wheel turns. Welcome change and notice the pattern behind coincidence.',
    'A roda gira. Acolha a mudança e perceba o padrão por trás da coincidência.',
    'Resistance to change or a run of bad luck. What goes down comes back up.',
    'Resistência à mudança ou uma fase de azar. O que desce volta a subir.'],
  ['11', 'Justice', 'A Justiça', ['truth', 'fairness', 'cause and effect'], ['verdade', 'justiça', 'causa e efeito'],
    'Clarity and accountability. Decisions made with integrity bring balance.',
    'Clareza e responsabilidade. Decisões tomadas com integridade trazem equilíbrio.',
    'Unfairness, dishonesty or avoiding consequences. Weigh things honestly.',
    'Injustiça, desonestidade ou fuga das consequências. Pese as coisas com honestidade.'],
  ['12', 'The Hanged Man', 'O Pendurado', ['surrender', 'pause', 'new perspective'], ['entrega', 'pausa', 'nova perspectiva'],
    'A sacred pause. Let go, see things upside down, and let insight arrive.',
    'Uma pausa sagrada. Solte, veja as coisas de cabeça para baixo e deixe o insight chegar.',
    'Stalling, martyrdom or resistance to letting go. The pause has served; move.',
    'Estagnação, martírio ou resistência a soltar. A pausa já serviu; mova-se.'],
  ['13', 'Death', 'A Morte', ['endings', 'transformation', 'renewal'], ['fins', 'transformação', 'renovação'],
    'An ending that clears the field. Something must fall so that something can grow.',
    'Um fim que limpa o campo. Algo precisa cair para que algo possa crescer.',
    'Clinging to what is over, fear of change. The old season is done.',
    'Apego ao que acabou, medo da mudança. A estação antiga terminou.'],
  ['14', 'Temperance', 'A Temperança', ['balance', 'patience', 'alchemy'], ['equilíbrio', 'paciência', 'alquimia'],
    'Blend opposites with patience. Moderation turns ingredients into gold.',
    'Misture opostos com paciência. A moderação transforma ingredientes em ouro.',
    'Excess, imbalance or impatience. Mix slower and taste as you go.',
    'Excesso, desequilíbrio ou impaciência. Misture devagar e prove enquanto faz.'],
  ['15', 'The Devil', 'O Diabo', ['attachment', 'materialism', 'shadow'], ['apego', 'materialismo', 'sombra'],
    'Notice the chains you agreed to wear. They are looser than they feel.',
    'Perceba as correntes que você aceitou usar. Elas são mais frouxas do que parecem.',
    'Breaking free, reclaiming power, facing the shadow. Release is possible.',
    'Libertação, retomada do poder, encarar a sombra. A libertação é possível.'],
  ['16', 'The Tower', 'A Torre', ['upheaval', 'revelation', 'liberation'], ['ruptura', 'revelação', 'libertação'],
    'Sudden collapse of what was built on false ground. Truth strikes like lightning.',
    'Colapso súbito do que foi construído sobre chão falso. A verdade atinge como um raio.',
    'Avoiding a necessary collapse or recovering from one. Rebuild on rock.',
    'Evitar um colapso necessário ou recuperar-se de um. Reconstrua sobre a rocha.'],
  ['17', 'The Star', 'A Estrela', ['hope', 'healing', 'inspiration'], ['esperança', 'cura', 'inspiração'],
    'Renewal after the storm. Pour yourself out with faith; you will be replenished.',
    'Renovação após a tempestade. Entregue-se com fé; você será reabastecido.',
    'Discouragement, lost faith or disconnection. The stars are still there.',
    'Desânimo, fé perdida ou desconexão. As estrelas ainda estão lá.'],
  ['18', 'The Moon', 'A Lua', ['illusion', 'fear', 'the unconscious'], ['ilusão', 'medo', 'inconsciente'],
    'Things are not as they seem. Walk gently through uncertainty and honour your instincts.',
    'As coisas não são o que parecem. Caminhe com cuidado pela incerteza e honre seus instintos.',
    'Confusion lifting, fears released, secrets surfacing. Clarity returns.',
    'A confusão se dissipa, medos são liberados, segredos vêm à tona. A clareza retorna.'],
  ['19', 'The Sun', 'O Sol', ['joy', 'vitality', 'success'], ['alegria', 'vitalidade', 'sucesso'],
    'Warmth, clarity and celebration. Let yourself be seen and be glad.',
    'Calor, clareza e celebração. Permita-se ser visto e alegre-se.',
    'Temporary gloom, inflated ego or delayed joy. The clouds will pass.',
    'Tristeza passageira, ego inflado ou alegria adiada. As nuvens vão passar.'],
  ['20', 'Judgement', 'O Julgamento', ['awakening', 'reckoning', 'calling'], ['despertar', 'acerto de contas', 'chamado'],
    'A call to rise. Review the past with honesty and answer what you are called to do.',
    'Um chamado para se erguer. Revise o passado com honestidade e responda ao que você é chamado a fazer.',
    'Self-doubt, harsh self-judgement or ignoring the call. Forgive and answer.',
    'Insegurança, autojulgamento severo ou ignorar o chamado. Perdoe e responda.'],
  ['21', 'The World', 'O Mundo', ['completion', 'wholeness', 'integration'], ['conclusão', 'plenitude', 'integração'],
    'A cycle completes. Everything is integrated; celebrate, then begin again.',
    'Um ciclo se completa. Tudo está integrado; celebre e depois recomece.',
    'Unfinished business, seeking closure. Tie the last thread before moving on.',
    'Assuntos pendentes, busca por encerramento. Amarre o último fio antes de seguir.'],
];

export const TAROT_MAJOR_FAMILY = 'tarot-major';

export const tarotMajorArcana: CardDef[] = rows.map(
  ([id, en, pt, kwEn, kwPt, upEn, upPt, revEn, revPt], i) => ({
    id,
    number: i,
    arcana: 'major',
    name: { en, 'pt-BR': pt },
    keywords: { en: kwEn, 'pt-BR': kwPt },
    meaning: {
      upright: { en: upEn, 'pt-BR': upPt },
      reversed: { en: revEn, 'pt-BR': revPt },
    },
  }),
);
