/**
 * The 56 Minor Arcana: four suits of ten pips and four court cards. Names,
 * keywords and short meanings in English and Brazilian Portuguese. Card ids
 * are `<suit>-<rank>` and match the image file names (`wands-01`, `cups-queen`).
 */
import type { CardDef } from '../engine/types';

export const SUITS = ['wands', 'cups', 'swords', 'pentacles'] as const;
export type Suit = (typeof SUITS)[number];

export const RANKS = ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', 'page', 'knight', 'queen', 'king'] as const;
export type Rank = (typeof RANKS)[number];

/** Minor cards are drawn at this fraction of the Major card size. */
export const MINOR_CARD_SCALE = 0.88;

export const minorCardId = (suit: Suit, rank: Rank) => `${suit}-${rank}`;

const suitName: Record<Suit, { en: string; pt: string }> = {
  wands: { en: 'Wands', pt: 'Paus' },
  cups: { en: 'Cups', pt: 'Copas' },
  swords: { en: 'Swords', pt: 'Espadas' },
  pentacles: { en: 'Pentacles', pt: 'Ouros' },
};

const rankName: Record<Rank, { en: string; pt: string }> = {
  '01': { en: 'Ace', pt: 'Ás' },
  '02': { en: 'Two', pt: 'Dois' },
  '03': { en: 'Three', pt: 'Três' },
  '04': { en: 'Four', pt: 'Quatro' },
  '05': { en: 'Five', pt: 'Cinco' },
  '06': { en: 'Six', pt: 'Seis' },
  '07': { en: 'Seven', pt: 'Sete' },
  '08': { en: 'Eight', pt: 'Oito' },
  '09': { en: 'Nine', pt: 'Nove' },
  '10': { en: 'Ten', pt: 'Dez' },
  page: { en: 'Page', pt: 'Pajem' },
  knight: { en: 'Knight', pt: 'Cavaleiro' },
  queen: { en: 'Queen', pt: 'Rainha' },
  king: { en: 'King', pt: 'Rei' },
};

type Row = [
  kwEn: string[],
  kwPt: string[],
  uprightEn: string,
  uprightPt: string,
  reversedEn: string,
  reversedPt: string,
];

/** Per suit, one row per rank in `RANKS` order. */
const rows: Record<Suit, Row[]> = {
  wands: [
    [['inspiration', 'spark', 'new venture'], ['inspiração', 'faísca', 'novo empreendimento'],
      'A spark of creative fire. Say yes to the idea that excites you and begin.',
      'Uma faísca de fogo criativo. Diga sim à ideia que te empolga e comece.',
      'Delays, a dull spark or an idea without a plan. Feed the fire before you build on it.',
      'Atrasos, uma faísca apagada ou uma ideia sem plano. Alimente o fogo antes de construir sobre ele.'],
    [['planning', 'decision', 'horizon'], ['planejamento', 'decisão', 'horizonte'],
      'You hold the world in your hand. Look at the horizon and choose a direction.',
      'Você tem o mundo na mão. Olhe o horizonte e escolha uma direção.',
      'Fear of the unknown or plans that never leave the room. Stop waiting for perfect conditions.',
      'Medo do desconhecido ou planos que não saem do papel. Pare de esperar as condições perfeitas.'],
    [['expansion', 'foresight', 'progress'], ['expansão', 'visão', 'progresso'],
      'The ships are sailing. Your effort is under way; watch for what returns.',
      'Os navios partiram. Seu esforço está em andamento; observe o que retorna.',
      'Obstacles, delays or thinking too small. Widen the view and be patient.',
      'Obstáculos, atrasos ou pensar pequeno demais. Amplie a visão e tenha paciência.'],
    [['celebration', 'home', 'harmony'], ['celebração', 'lar', 'harmonia'],
      'A milestone worth celebrating. Stability, belonging and a place to call home.',
      'Um marco que merece celebração. Estabilidade, pertencimento e um lugar para chamar de lar.',
      'Instability at home or a celebration postponed. Build the foundation first.',
      'Instabilidade em casa ou uma celebração adiada. Construa primeiro a base.'],
    [['competition', 'conflict', 'tension'], ['competição', 'conflito', 'tensão'],
      'Clashing wills and scattered energy. Rivalry can sharpen you if you keep it fair.',
      'Vontades em choque e energia dispersa. A rivalidade pode te afiar se for justa.',
      'Conflict avoided or resolved. Agreement is close; let go of the need to win.',
      'Conflito evitado ou resolvido. O acordo está próximo; solte a necessidade de vencer.'],
    [['victory', 'recognition', 'confidence'], ['vitória', 'reconhecimento', 'confiança'],
      'Public success and applause. Accept the recognition you have earned.',
      'Sucesso público e aplausos. Aceite o reconhecimento que você conquistou.',
      'Ego, a fall from grace or praise that never came. Measure yourself by your own standard.',
      'Ego, uma queda em desgraça ou o elogio que não veio. Meça-se pelo seu próprio padrão.'],
    [['defence', 'perseverance', 'challenge'], ['defesa', 'perseverança', 'desafio'],
      'Hold your ground. You have the high position; keep it with courage.',
      'Mantenha sua posição. Você está no ponto alto; sustente-o com coragem.',
      'Feeling overwhelmed or giving up too soon. Choose which battles are yours.',
      'Sentir-se sobrecarregado ou desistir cedo demais. Escolha quais batalhas são suas.'],
    [['speed', 'movement', 'news'], ['rapidez', 'movimento', 'notícias'],
      'Things move fast now. Messages arrive, plans take flight; act while the air is clear.',
      'As coisas andam rápido agora. Mensagens chegam, planos decolam; aja enquanto o ar está limpo.',
      'Delays, missed connections or haste without aim. Slow down and re-aim.',
      'Atrasos, desencontros ou pressa sem direção. Desacelere e mire de novo.'],
    [['resilience', 'last stand', 'boundaries'], ['resiliência', 'última defesa', 'limites'],
      'Wounded but standing. One more push; you are closer than you feel.',
      'Ferido, mas de pé. Mais um esforço; você está mais perto do que sente.',
      'Exhaustion, paranoia or refusing help. Lower the guard where it is safe to.',
      'Exaustão, paranoia ou recusa de ajuda. Baixe a guarda onde for seguro.'],
    [['burden', 'responsibility', 'overload'], ['fardo', 'responsabilidade', 'sobrecarga'],
      'Carrying too much alone. The goal is near, but not everything must come with you.',
      'Carregando demais sozinho. A meta está perto, mas nem tudo precisa ir junto.',
      'Setting burdens down, delegating or collapsing under the weight. Release what is not yours.',
      'Deixar fardos no chão, delegar ou desabar sob o peso. Solte o que não é seu.'],
    [['curiosity', 'enthusiasm', 'messenger'], ['curiosidade', 'entusiasmo', 'mensageiro'],
      'A fresh, eager energy or good news about a creative pursuit. Explore freely.',
      'Uma energia nova e ávida ou boas notícias sobre um projeto criativo. Explore livremente.',
      'Restlessness, half-starts or bad news about a plan. Find a focus for the excitement.',
      'Inquietação, começos pela metade ou más notícias sobre um plano. Encontre um foco para a empolgação.'],
    [['passion', 'adventure', 'impulse'], ['paixão', 'aventura', 'impulso'],
      'Charge ahead with passion. Bold action, travel, a burst of confidence.',
      'Avance com paixão. Ação ousada, viagem, uma explosão de confiança.',
      'Recklessness, anger or a project stalled by impatience. Direct the heat.',
      'Imprudência, raiva ou um projeto travado pela impaciência. Direcione o calor.'],
    [['warmth', 'charisma', 'independence'], ['calor', 'carisma', 'independência'],
      'Confident, generous and magnetic. Lead with warmth and trust your own light.',
      'Confiante, generosa e magnética. Lidere com calor e confie na própria luz.',
      'Jealousy, demanding attention or dimmed confidence. Return to what makes you glow.',
      'Ciúme, exigir atenção ou confiança apagada. Volte ao que te faz brilhar.'],
    [['vision', 'leadership', 'boldness'], ['visão', 'liderança', 'ousadia'],
      'A visionary leader. Set the direction and inspire others to follow.',
      'Um líder visionário. Defina a direção e inspire os outros a seguir.',
      'Tyranny, impulsiveness or a vision without follow-through. Lead by example, not by force.',
      'Tirania, impulsividade ou uma visão sem continuidade. Lidere pelo exemplo, não pela força.'],
  ],
  cups: [
    [['love', 'new feeling', 'openness'], ['amor', 'novo sentimento', 'abertura'],
      'The heart overflows. A new emotional beginning, compassion, creative flow.',
      'O coração transborda. Um novo começo emocional, compaixão, fluxo criativo.',
      'Emotions blocked or a cup drained. Refill yourself before pouring for others.',
      'Emoções bloqueadas ou uma taça vazia. Encha-se antes de servir aos outros.'],
    [['partnership', 'attraction', 'mutual respect'], ['parceria', 'atração', 'respeito mútuo'],
      'Two hearts meet as equals. A bond, a reconciliation, a partnership that heals.',
      'Dois corações se encontram como iguais. Um vínculo, uma reconciliação, uma parceria que cura.',
      'Imbalance, a break-up or miscommunication. Restore honesty between you.',
      'Desequilíbrio, um rompimento ou falha de comunicação. Restaure a honestidade entre vocês.'],
    [['friendship', 'community', 'celebration'], ['amizade', 'comunidade', 'celebração'],
      'Raise a glass with your people. Joy shared is joy multiplied.',
      'Erga a taça com sua gente. Alegria compartilhada é alegria multiplicada.',
      'Gossip, isolation or too much of a good thing. Choose your circle with care.',
      'Fofoca, isolamento ou excesso de algo bom. Escolha seu círculo com cuidado.'],
    [['apathy', 'contemplation', 'missed offer'], ['apatia', 'contemplação', 'oferta ignorada'],
      'Bored with what you have, blind to what is offered. Look at the cup being handed to you.',
      'Entediado com o que tem, cego ao que é oferecido. Olhe a taça que estão te entregando.',
      'Awakening from apathy, new interest, accepting the offer. Say yes.',
      'Despertar da apatia, novo interesse, aceitar a oferta. Diga sim.'],
    [['loss', 'grief', 'regret'], ['perda', 'luto', 'arrependimento'],
      'Mourning what was spilled. Grieve, then turn around: two cups still stand.',
      'Lamentando o que foi derramado. Chore, depois vire-se: duas taças ainda estão de pé.',
      'Acceptance, moving on, forgiveness. The loss has taught what it came to teach.',
      'Aceitação, seguir em frente, perdão. A perda ensinou o que veio ensinar.'],
    [['nostalgia', 'innocence', 'memory'], ['nostalgia', 'inocência', 'memória'],
      'Sweet memories, a gift from the past, childlike joy. Let the past nourish you.',
      'Doces lembranças, um presente do passado, alegria de criança. Deixe o passado te nutrir.',
      'Stuck in the past or refusing to grow up. Keep the sweetness, leave the rest.',
      'Preso ao passado ou recusa em crescer. Guarde a doçura, deixe o resto.'],
    [['choices', 'illusion', 'fantasy'], ['escolhas', 'ilusão', 'fantasia'],
      'Many tempting options, few of them real. Dream, then pick one and act.',
      'Muitas opções tentadoras, poucas reais. Sonhe, depois escolha uma e aja.',
      'Clarity after confusion, or a hard dose of reality. Commit to what is solid.',
      'Clareza após a confusão, ou uma dose dura de realidade. Comprometa-se com o que é sólido.'],
    [['walking away', 'search', 'letting go'], ['partida', 'busca', 'desapego'],
      'Leaving something that no longer fills you to seek what does. A brave departure.',
      'Deixar algo que já não te preenche para buscar o que preenche. Uma partida corajosa.',
      'Fear of leaving, drifting, or a return. Ask what you are truly looking for.',
      'Medo de partir, andar à deriva ou um retorno. Pergunte o que você realmente busca.'],
    [['satisfaction', 'wish', 'contentment'], ['satisfação', 'desejo', 'contentamento'],
      'The wish card. Contentment, comfort, a moment to enjoy what you have made.',
      'A carta do desejo. Contentamento, conforto, um momento para curtir o que você construiu.',
      'Smugness, indulgence or a wish that leaves you hungry. Satisfaction is inside, not on the shelf.',
      'Presunção, excesso ou um desejo que deixa fome. A satisfação está dentro, não na prateleira.'],
    [['harmony', 'family', 'fulfilment'], ['harmonia', 'família', 'plenitude'],
      'A rainbow over the home. Emotional fulfilment, loving bonds, lasting happiness.',
      'Um arco-íris sobre o lar. Plenitude emocional, laços amorosos, felicidade duradoura.',
      'Domestic tension, broken harmony or a picture-perfect facade. Tend the real relationships.',
      'Tensão doméstica, harmonia quebrada ou uma fachada perfeita. Cuide das relações reais.'],
    [['creative message', 'sensitivity', 'surprise'], ['mensagem criativa', 'sensibilidade', 'surpresa'],
      'A gentle, imaginative message; a new feeling surfacing. Follow the fish in the cup.',
      'Uma mensagem suave e imaginativa; um novo sentimento surgindo. Siga o peixe na taça.',
      'Emotional immaturity, a creative block or a daydream ignored. Take the feeling seriously.',
      'Imaturidade emocional, um bloqueio criativo ou um devaneio ignorado. Leve o sentimento a sério.'],
    [['romance', 'charm', 'proposal'], ['romance', 'charme', 'proposta'],
      'The romantic on a white horse. An offer from the heart, art and idealism in motion.',
      'O romântico no cavalo branco. Uma oferta do coração, arte e idealismo em movimento.',
      'Moodiness, unrealistic promises or disappointment. Ground the ideal in action.',
      'Instabilidade de humor, promessas irreais ou decepção. Aterre o ideal na ação.'],
    [['compassion', 'intuition', 'calm'], ['compaixão', 'intuição', 'calma'],
      'Deep empathy and emotional wisdom. Hold space for others without losing yourself.',
      'Empatia profunda e sabedoria emocional. Acolha os outros sem se perder.',
      'Overwhelm, martyrdom or emotional manipulation. Protect your own waters.',
      'Sobrecarga, martírio ou manipulação emocional. Proteja suas próprias águas.'],
    [['balance', 'diplomacy', 'emotional maturity'], ['equilíbrio', 'diplomacia', 'maturidade emocional'],
      'Steady on a moving sea. Feel deeply, act wisely, lead with kindness.',
      'Firme sobre um mar em movimento. Sinta fundo, aja com sabedoria, lidere com bondade.',
      'Coldness, repressed feelings or moods that flood everyone around. Let the sea settle.',
      'Frieza, sentimentos reprimidos ou humores que inundam todos ao redor. Deixe o mar acalmar.'],
  ],
  swords: [
    [['clarity', 'breakthrough', 'truth'], ['clareza', 'avanço', 'verdade'],
      'A sharp new idea cuts through the fog. See clearly and speak plainly.',
      'Uma ideia nova e afiada corta a névoa. Veja com clareza e fale com franqueza.',
      'Confusion, a cruel truth or a mind spinning without focus. Sheath the blade until you can see.',
      'Confusão, uma verdade cruel ou uma mente girando sem foco. Guarde a lâmina até enxergar.'],
    [['stalemate', 'avoidance', 'difficult choice'], ['impasse', 'evitação', 'escolha difícil'],
      'Blindfolded between two blades. The decision waits for you to remove the blindfold.',
      'Vendado entre duas lâminas. A decisão espera que você tire a venda.',
      'The stalemate breaks, information arrives, or you are overwhelmed by the choice. Decide with what you know.',
      'O impasse se rompe, informações chegam, ou a escolha te sufoca. Decida com o que sabe.'],
    [['heartbreak', 'pain', 'grief'], ['coração partido', 'dor', 'luto'],
      'A painful truth pierces the heart. Feel it fully; the storm passes.',
      'Uma verdade dolorosa atravessa o coração. Sinta por inteiro; a tempestade passa.',
      'Healing, forgiveness, releasing old pain. Or a wound you refuse to look at.',
      'Cura, perdão, liberar uma dor antiga. Ou uma ferida que você se recusa a olhar.'],
    [['rest', 'recovery', 'retreat'], ['descanso', 'recuperação', 'recolhimento'],
      'Lay the swords down and rest. Recovery is not retreat from the fight but preparation for it.',
      'Deixe as espadas e descanse. Recuperar-se não é fugir da luta, é preparar-se para ela.',
      'Restlessness, burnout or coming back to life. Rest before the body forces you to.',
      'Inquietação, esgotamento ou volta à vida. Descanse antes que o corpo te obrigue.'],
    [['conflict', 'hollow victory', 'defeat'], ['conflito', 'vitória vazia', 'derrota'],
      'Winning at a cost. Ask whether this fight is worth what it takes from you.',
      'Vencer a um custo. Pergunte se esta luta vale o que ela tira de você.',
      'Reconciliation, remorse or letting a grudge go. Put the swords down first.',
      'Reconciliação, remorso ou deixar um rancor ir. Baixe as espadas primeiro.'],
    [['transition', 'passage', 'moving on'], ['transição', 'travessia', 'seguir em frente'],
      'Crossing to calmer waters. Leave the trouble behind, one steady stroke at a time.',
      'Atravessando para águas mais calmas. Deixe o problema para trás, uma remada firme de cada vez.',
      'Stuck in troubled waters, resisting the crossing or unfinished business. Let the boat move.',
      'Preso em águas turbulentas, resistindo à travessia ou assuntos pendentes. Deixe o barco andar.'],
    [['strategy', 'stealth', 'deception'], ['estratégia', 'astúcia', 'engano'],
      'Cleverness, or sneaking away with what is not yours. Be strategic without being dishonest.',
      'Esperteza, ou escapar com o que não é seu. Seja estratégico sem ser desonesto.',
      'A confession, getting caught or self-deception uncovered. Come clean.',
      'Uma confissão, ser pego ou um autoengano revelado. Fale a verdade.'],
    [['restriction', 'self-imposed limits', 'fear'], ['restrição', 'limites autoimpostos', 'medo'],
      'Bound only by what you believe. The ties are loose; the blindfold is yours to remove.',
      'Preso apenas pelo que acredita. Os laços estão frouxos; a venda é sua para tirar.',
      'Release from restriction, new perspective, freedom. Step out of the circle.',
      'Libertação da restrição, nova perspectiva, liberdade. Saia do círculo.'],
    [['anxiety', 'nightmares', 'worry'], ['ansiedade', 'pesadelos', 'preocupação'],
      'Sleepless with worry. Most of the swords on the wall exist only at night.',
      'Insone de preocupação. A maioria das espadas na parede só existe à noite.',
      'Hope returning, fears faced, or despair deepening. Speak the fear out loud.',
      'Esperança voltando, medos enfrentados, ou desespero se aprofundando. Diga o medo em voz alta.'],
    [['ending', 'rock bottom', 'betrayal'], ['fim', 'fundo do poço', 'traição'],
      'A painful, final ending. The worst is over; the sky is already brightening.',
      'Um fim doloroso e definitivo. O pior passou; o céu já está clareando.',
      'Recovery, survival, or dragging out an ending. Let it be finished.',
      'Recuperação, sobrevivência, ou prolongar um fim. Deixe terminar.'],
    [['curiosity', 'vigilance', 'new ideas'], ['curiosidade', 'vigilância', 'novas ideias'],
      'A quick mind on alert. Ask questions, gather facts, stay honest.',
      'Uma mente rápida em alerta. Faça perguntas, junte fatos, seja honesto.',
      'Gossip, spying or all talk and no action. Use the mind to build, not to cut.',
      'Fofoca, espionagem ou muita conversa e pouca ação. Use a mente para construir, não para cortar.'],
    [['ambition', 'directness', 'haste'], ['ambição', 'franqueza', 'pressa'],
      'Charging straight at the goal. Decisive, fast and fearless; mind who is in the path.',
      'Investindo direto contra a meta. Decidido, rápido e destemido; cuidado com quem está no caminho.',
      'Rashness, aggression or a blade with no direction. Aim before you charge.',
      'Precipitação, agressividade ou uma lâmina sem direção. Mire antes de investir.'],
    [['perception', 'independence', 'honesty'], ['percepção', 'independência', 'honestidade'],
      'Clear-eyed and unsentimental. Say what is true, set boundaries, keep your wit.',
      'Olhar claro e sem sentimentalismo. Diga o que é verdade, imponha limites, mantenha a inteligência.',
      'Bitterness, coldness or cruelty with words. Truth without kindness wounds.',
      'Amargura, frieza ou crueldade com as palavras. A verdade sem bondade fere.'],
    [['authority', 'reason', 'judgement'], ['autoridade', 'razão', 'julgamento'],
      'Intellectual authority. Rule by reason and fairness; decide with a clear head.',
      'Autoridade intelectual. Governe pela razão e pela justiça; decida com a cabeça clara.',
      'Abuse of power, manipulation or cold rigidity. Let logic serve people, not the other way round.',
      'Abuso de poder, manipulação ou rigidez fria. A lógica deve servir às pessoas, não o contrário.'],
  ],
  pentacles: [
    [['opportunity', 'prosperity', 'seed'], ['oportunidade', 'prosperidade', 'semente'],
      'A gift from the earth: a new job, an offer, a seed of prosperity. Plant it.',
      'Um presente da terra: um novo trabalho, uma oferta, uma semente de prosperidade. Plante-a.',
      'A missed chance, poor planning or greed. Check the soil before you plant.',
      'Uma chance perdida, planejamento ruim ou ganância. Verifique o solo antes de plantar.'],
    [['balance', 'juggling', 'adaptability'], ['equilíbrio', 'malabarismo', 'adaptabilidade'],
      'Juggling priorities with grace. Stay flexible; the waves keep moving.',
      'Fazendo malabarismo com as prioridades. Mantenha-se flexível; as ondas continuam.',
      'Dropping the ball, overcommitting or financial disorganisation. Simplify.',
      'Deixar a bola cair, assumir demais ou desorganização financeira. Simplifique.'],
    [['teamwork', 'craft', 'collaboration'], ['trabalho em equipe', 'ofício', 'colaboração'],
      'Skilled work recognised and shared. Build with others; each brings a part.',
      'Trabalho de qualidade reconhecido e compartilhado. Construa com os outros; cada um traz uma parte.',
      'Disharmony at work, sloppy craft or going it alone. Respect every role.',
      'Desarmonia no trabalho, ofício malfeito ou seguir sozinho. Respeite cada papel.'],
    [['security', 'control', 'saving'], ['segurança', 'controle', 'economia'],
      'Holding on tight to what you have. Stability is good; a clenched fist cannot receive.',
      'Segurando firme o que você tem. Estabilidade é boa; uma mão fechada não recebe.',
      'Generosity, letting go of control, or reckless spending. Find the middle grip.',
      'Generosidade, soltar o controle, ou gastos imprudentes. Encontre o meio-termo.'],
    [['hardship', 'loss', 'isolation'], ['dificuldade', 'perda', 'isolamento'],
      'Out in the cold, walking past the lit window. Help is nearer than it looks; ask for it.',
      'No frio, passando pela janela iluminada. A ajuda está mais perto do que parece; peça.',
      'Recovery from hardship, finding shelter, renewed faith. The worst is behind you.',
      'Recuperação da dificuldade, encontrar abrigo, fé renovada. O pior ficou para trás.'],
    [['generosity', 'charity', 'give and take'], ['generosidade', 'caridade', 'dar e receber'],
      'Giving and receiving in balance. Share what you have; accept what is offered.',
      'Dar e receber em equilíbrio. Compartilhe o que tem; aceite o que é oferecido.',
      'Strings attached, debt or one-sided giving. Check the balance of power.',
      'Condições ocultas, dívida ou doação unilateral. Confira o equilíbrio de poder.'],
    [['patience', 'investment', 'assessment'], ['paciência', 'investimento', 'avaliação'],
      'Leaning on the hoe, watching the crop grow. Long-term effort is paying off; be patient.',
      'Apoiado na enxada, vendo a plantação crescer. O esforço de longo prazo está compensando; tenha paciência.',
      'Impatience, poor returns or effort with no reward. Reassess where you are sowing.',
      'Impaciência, retorno fraco ou esforço sem recompensa. Reavalie onde está semeando.'],
    [['diligence', 'skill', 'apprenticeship'], ['dedicação', 'habilidade', 'aprendizado'],
      'Mastery through repetition. Do the work carefully, one coin at a time.',
      'Maestria pela repetição. Faça o trabalho com cuidado, uma moeda de cada vez.',
      'Perfectionism, tedium or cutting corners. Remember why you learned this craft.',
      'Perfeccionismo, tédio ou atalhos malfeitos. Lembre por que você aprendeu este ofício.'],
    [['abundance', 'self-sufficiency', 'luxury'], ['abundância', 'autossuficiência', 'luxo'],
      'Enjoying the garden you grew. Independence, refinement, well-earned comfort.',
      'Aproveitando o jardim que você cultivou. Independência, refinamento, conforto bem merecido.',
      'Over-dependence, living beyond your means or working without enjoying. Savour the fruit.',
      'Dependência excessiva, viver acima das posses ou trabalhar sem aproveitar. Saboreie o fruto.'],
    [['legacy', 'wealth', 'family'], ['legado', 'riqueza', 'família'],
      'Lasting wealth across generations. Roots, inheritance, a home that endures.',
      'Riqueza duradoura através das gerações. Raízes, herança, um lar que perdura.',
      'Family disputes over money, instability or a legacy questioned. Values before valuables.',
      'Disputas familiares por dinheiro, instabilidade ou um legado questionado. Valores antes dos bens.'],
    [['study', 'ambition', 'new skill'], ['estudo', 'ambição', 'nova habilidade'],
      'A student of the practical. A new course, job or skill; good news about money.',
      'Um estudante do prático. Um novo curso, trabalho ou habilidade; boas notícias sobre dinheiro.',
      'Procrastination, distraction or a plan without ground. Take the first concrete step.',
      'Procrastinação, distração ou um plano sem base. Dê o primeiro passo concreto.'],
    [['reliability', 'routine', 'hard work'], ['confiabilidade', 'rotina', 'trabalho duro'],
      'Slow, steady and dependable. Not glamorous, but the field gets ploughed.',
      'Lento, constante e confiável. Sem glamour, mas o campo é arado.',
      'Boredom, stagnation or stubbornness. Steadiness is a virtue; inertia is not.',
      'Tédio, estagnação ou teimosia. Constância é virtude; inércia não.'],
    [['nurturing', 'practicality', 'abundance'], ['cuidado', 'praticidade', 'abundância'],
      'Warm, grounded and generous. Care for body, home and the people in it.',
      'Calorosa, centrada e generosa. Cuide do corpo, do lar e das pessoas nele.',
      'Self-neglect, smothering or worry about money. Nurture yourself as you nurture others.',
      'Descuido consigo, superproteção ou preocupação com dinheiro. Cuide de si como cuida dos outros.'],
    [['wealth', 'security', 'mastery'], ['riqueza', 'segurança', 'maestria'],
      'The steward of abundance. Success built patiently; share it with wisdom.',
      'O guardião da abundância. Sucesso construído com paciência; compartilhe com sabedoria.',
      'Greed, materialism or a stubborn refusal to change. Wealth is a tool, not a throne.',
      'Ganância, materialismo ou uma recusa teimosa em mudar. Riqueza é ferramenta, não trono.'],
  ],
};

export const TAROT_MINOR_ARCANA_COUNT = SUITS.length * RANKS.length;

export const tarotMinorArcana: CardDef[] = SUITS.flatMap((suit) =>
  RANKS.map((rank, i): CardDef => {
    const [kwEn, kwPt, upEn, upPt, revEn, revPt] = rows[suit][i]!;
    return {
      id: minorCardId(suit, rank),
      arcana: 'minor',
      suit,
      rank,
      scale: MINOR_CARD_SCALE,
      name: { en: `${rankName[rank].en} of ${suitName[suit].en}`, 'pt-BR': `${rankName[rank].pt} de ${suitName[suit].pt}` },
      keywords: { en: kwEn, 'pt-BR': kwPt },
      meaning: {
        upright: { en: upEn, 'pt-BR': upPt },
        reversed: { en: revEn, 'pt-BR': revPt },
      },
    };
  }),
);
